### ISSUE TITLE
Convert existing datacamp repo into learnr package or create a whole new learnr repo? 

### ISSUE THREAD

**Issue by lwjohnst86** [lwjohnst86/campout#2]
What would be the best solution here? I initially thought of just converting my repo into the learnr package, but with @reuning 's code in the PR, made me think different.

@apreshill and @reuning, thoughts?

**Comment by reuning** [comment]
So I guess the workflow for using this that I saw was:

1) You clone your datacamp course.
2) You use campout to convert that course into a learnr package. 
3) You do what you want with the new learnr package. 

If you have multiple datacamp courses then you can use campout on all the different courses.
